### ISSUE TITLE
No way to set center=false if center-default is true

### ISSUE THREAD

**Issue by mecha1** [farrellm/scad-clj#22]
If center-default is true (which is the default), there is no way to selectively set center=false for an individual shape. E.g. the following:

(cube 100 50 10 :center false)

will still generate scad with center=true:

cube ([100, 50, 10], center=true);

This is because the various write-expr methods in scad-cli.scad treat the center parameter like this:

(when center ", center=true")

That is, they only do something when the center parameter is true. If the center param is false, nothing happens and the default behavior prevails, which is to set center to true.

**Comment by farrellm** [comment]
Yes, certainly sounds like a bug. I'll look in to it.

**Comment by farrellm** [comment]
Fixed in version 0.4.1
