### ISSUE TITLE
Support for OpenSCAD text()

### ISSUE THREAD

**Issue by mecha1** [farrellm/scad-clj#24]
It would be great if scad-clj could support the new(ish) OpenSCAD text() function directly. Currently it looks like scad-clj is doing some magic to generate text as polygons, but it would be much simpler/nicer if the native text() function could be used: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_the_2D_Subsystem#Text

**Comment by mecha1** [comment]
I created a pull request to add this functionality: farrellm/scad-clj#25. I replaced the scad-clj.model/text function with a new version that implements native openscad text rendering and renamed the existing text function to polygon-text. Please feel free to modify as you see fit -

**Comment by farrellm** [comment]
Merged, thank you!
