### ISSUE TITLE
with-f* functions do not work

### ISSUE THREAD

**Issue by mecha1** [farrellm/scad-clj#26]
Unless I am misunderstanding how they are meant to be used, it seems like none of the with-f* functions work correctly. If I try using, e.g. (with-fs 0.1 ...), I get the error 'Unable to resolve *fs* in this context', presumably because the symbol is not namespace qualified in the definition of with-fs. But if I try doing (with-f* 'scad-clj.model/*fs* 0.1 ...), I get the error 'nth not supported on this type: Symbol' from line 9 of scad-clj.scad, which is the multimethod definition of write-expr.

**Comment by farrellm** [comment]
My apologies for the delay-

I think I see the problem. "with-*" are macros; I always "refer" the whole namespace, so I never had a problem.

**Comment by farrellm** [comment]
Fixed.
https://github.com/farrellm/scad-clj/commit/fc6cd44e47ad5853363be33e9dd75506288040e9
