### ISSUE TITLE
I've added scad-clj to list of code-cad projects.

### ISSUE THREAD

**Issue by Irev-Dev** [farrellm/scad-clj#48]
Hey @farrellm  👋,

I recently put together a list of all of the code-CAD projects that I know of [here](https://kurthutten.com/blog/curated-code-cad), and also on [Github](https://github.com/Irev-Dev/curated-code-cad). I stumbled across scad-clj today and have added it. As a brief summary I wrote:

OpenSCAD DSL in Clojure. Functions generally mirror OpenSCAD, with a couple of notable exceptions.

Though I would love some feedback from you if you want to add or change it? The context is that it's in a list with many other code-cad projects, so information about how it differentiates is most useful.

Cheers,
Kurt

**Comment by farrellm** [comment]
Hey Kurt,

Thanks for reaching out! That all looks fine. I would add that, if you’re interested, I also have a new one, as my preferred language has changed: 
https://github.com/farrellm/scad-hs

Best, Matt

**Comment by Irev-Dev** [comment]
Thanks @farrellm,

I've added it too.
